# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76fd4fbe76928b832378318dbe5a808d3eba9d301611bfb01763bbad0d2bb675aacd14fcf6243c41e2a1b575decea0ad1717ae39f101a2238da692d93cb4f515

test:
  secret_key_base: d24167d05a6ee87dcd5577764d8354809fb980ead949a1fac6e11a85479cade9212ec3a28cc41645f5b9b523f4580a4e68f6640c8a8a6957ba3687a20e61eee3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
